FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# Use this environment variable to ensure proper hot reloading
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "start"]
