version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/expenditure-db
      - MONGO_URI=mongodb+srv://alikomurcu:<5wIMugWfs9GS4usl>@cluster0.c7eou.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=my_jwt_secret
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodb_data:
