version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: expenditure_mongo
    ports:
      - "27017:27017"

  backend:
    container_name: expenditure_app_backend
    build:
      context: ./backend
    ports:
      - "3001:3001"  # Expose the container's port 3001 to your machine
    volumes:
      - ./backend:/usr/src/app  # Mount the backend code in the container
      - /usr/src/app/node_modules  # Avoid overriding node_modules
    command: npm run dev
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/expenditure-db

  frontend:
    build:
      context: ./frontend  # Assuming your frontend code is in a 'frontend' folder
    container_name: expenditure_app_frontend
    ports:
      - "3000:3000"  # Assuming your frontend runs on port 3000
    depends_on:
      - backend