services:
  - type: web
    name: expense-tracker-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
